name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run controller tests
      run: npm run test-controller
    
    - name: Start the application 
      run: npm start & 

    - name: Wait for the application REST to be ready
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:3000; then
            echo "Application is ready"
            break
          else
            echo "Waiting for application to be ready..."
            sleep 5
          fi
        done

    - name: Run external tests
      run: npm run test-external

    
    - name: Start the application GraphQL
      run: npm run start:graphql &

    - name: Wait for the application graphql to be ready
      run: |
        for i in {1..15}; do
          if curl -s http://localhost:4000; then
            echo "GraphQL server is ready"
            break
          else
            echo "Waiting for GraphQL server to be ready..."
            sleep 5
          fi
        done

    - name: Run GraphQL tests
      run: npm run test-graphql
